package kayu.exception;

/**
 * DukeException class.
 *
 * This exception class helps manage exceptions generated by the whole project.
 */
public class DukeException extends Exception {

    /**
     * Initializes a DukeException instance for use in module.
     * 
     * @param message String message to describe error faced.
     */
    public DukeException(String message) {
        super(message);
    }
}
