package kayu.exception;

/**
 * Manages exceptions generated by the whole project operations.
 */
public class DukeException extends Exception {

    /**
     * Initializes a DukeException instance for use in module.
     * 
     * @param message String message to describe error faced.
     */
    public DukeException(String message) {
        super(message);
    }
}
