package kayu.exception;

/**
 * DukeException class.
 *
 * This exception class helps manage exceptions generated by the whole project.
 */
public class DukeException extends Exception {

    public DukeException(String message) {
        super(message);
    }
}
