package kayu.exception;

/**
 * Manages exceptions generated by the whole project operations.
 */
public class KayuException extends Exception {

    /**
     * Initializes a DukeException instance for use in module.
     *
     * @param message String message to describe error faced.
     */
    public KayuException(String message) {
        super(message);
    }
}
