package kayu.exception;

/**
 * StorageException class.
 *
 * This exception class helps manage exceptions generated by 
 * {@link kayu.storage.Storage} and {@link kayu.service.TaskList}.
 */
public class StorageException extends Exception {

    /**
     * Initializes a StorageException instance for use in module.
     *
     * @param message String message to describe error faced.
     */
    public StorageException(String message) {
        super(message);
    }
}
