package kayu.exception;

/**
 * Manages exceptions generated by {@link kayu.storage.Storage} and {@link kayu.service.TaskList}
 * when accessing files or writing to them.
 */
public class StorageException extends Exception {

    /**
     * Initializes a StorageException instance for use in module.
     *
     * @param message String message to describe error faced.
     */
    public StorageException(String message) {
        super(message);
    }
}
