public enum DukeExceptionType {

    DEADLINEDESC, DEADLINETIME, EVENTDESC, EVENTPERIOD, TODODESC, INVALIDDONE, INVALIDDELETE, INVALIDINPUT, DB_LAUNCH, 
    DB_READ, DB_ADD, DB_DONE, DB_DELETE, INVALIDFIND, INVALIDDATETIME, INVALIDPERIOD
}
