public enum DukeExceptionType {

    DEADLINEDESC, DEADLINETIME, EVENTDESC, EVENTPERIOD, TODODESC, INVALIDINDEX, INVALIDINPUT, DB_LAUNCH, DB_READ, 
    DB_ADD, DB_DONE, DB_DELETE, INVALIDFIND, INVALIDDATETIME, INVALIDPERIOD
}
