package exception;

/**
 * DukeException class.
 *
 * This exception class helps manage exceptions generated by Tasks.
 */
public class DukeException extends Exception {

    /**
     * Constructor that uses its parent class's.
     *
     * @param message message associated to error face
     */
    public DukeException(String message) {
        super(message);
    }
}
