package exception;

public enum DukeExceptionType {
    DEADLINE_DESC, DEADLINE_TIME, EVENT_DESC, EVENT_PERIOD, TODO_DESC, INVALID_INDEX, INVALID_INPUT, DB_LAUNCH, DB_READ, 
    DB_ADD, DB_DONE, DB_DELETE, INVALID_FIND, INVALID_DATETIME, INVALID_PERIOD, MISSING_FIND_DATE, MISSING_FIND_KEYWORD
}
