package exception;

/**
 * An enumeration of all possible DukeExceptions.
 */
public enum DukeExceptionType {
    DB_ADD, DB_DELETE, DB_DONE, DB_LAUNCH, DB_READ, INVALID_DATETIME, INVALID_FIND, INVALID_INPUT, INVALID_PERIOD, 
    INVALID_TASK_INDEX, MISSING_DEADLINE_DATETIME, MISSING_DEADLINE_DESC, MISSING_EVENT_DESC, MISSING_EVENT_PERIOD,
    MISSING_FIND_DATE, MISSING_FIND_KEYWORD, MISSING_TODO_DESC
}
