package exception;

/**
 * StorageException class.
 *
 * This exception class helps manage exceptions generated by Storage.
 */
public class StorageException extends Exception {

    /**
     * Constructor that uses its parent class's.
     *
     * @param message message associated to error face
     */
    public StorageException(String message) {
        super(message);
    }
}
