package exception;

/**
 * TaskManagerException class.
 *
 * This exception class helps manage exceptions generated by Tasks.
 */
public class TaskManagerException extends Exception {

    /**
     * Constructor that uses its parent class's.
     *
     * @param message message associated to error face
     */
    public TaskManagerException(String message) {
        super(message);
    }
}
