remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: DukeBot
description: A task manager - Type away to schedule your day
logo: https://wiki.openjdk.java.net/display/duke/Gallery?preview=/http%3A%2F%2Fcr.openjdk.java.net%2F~jeff%2FDuke%2Fpng%2FThumbsup2.png
