theme: jekyll-theme-minimal
title: DukeBot
description: A task manager - Type away to schedule your day
logo: https://wiki.openjdk.java.net/display/duke/Gallery?preview=/http%3A%2F%2Fcr.openjdk.java.net%2F~jeff%2FDuke%2Fpng%2FThumbsup2.png