name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Set up repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx

      - name: Install dos2unix (*NIX)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install dos2unix

      - name: Install dos2unix (MacOS)
        if: always() && runner.os == 'macOS'
        run: brew install dos2unix

      - name: Build and check with Gradle
        run: ./gradlew check

      - name: Perform IO redirection test (*NIX)
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh

      - name: Perform IO redirection test (MacOS)
        if: always() && runner.os == 'macOS'
        working-directory:  ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh

      - name: Perform IO redirection test (Windows)
        if: always() && runner.os == 'Windows'
        working-directory:  ${{ github.workspace }}/text-ui-test
        shell: cmd
        run: runtest.bat

      - name: Build and check with Gradle
        run: ./gradlew check coverage

      - uses: codecov/codecov-action@v1
        if: runner.os == 'Linux'
        with:
          file: ${{ github.workspace }}/build/reports/jacoco/coverage/coverage.xml
          fail_ci_if_error: true
